<?php
	/** @var \MvcCore\View $this */

	/** @var \MvcCore\Ext\Routers\IMedia $router */
	$router = $controller->GetRouter();
	/** @var \MvcCore\Request $request */
	$request = $controller->GetRequest();

	$mediaSiteKeysAndUrlPrefixes = $router->GetAllowedMediaVersionsAndUrlValues();
	$mediaVersionsCount = count($mediaSiteKeysAndUrlPrefixes);
	$fullUrl = $request->GetFullUrl();
	$mediaVersionUrlParam = \MvcCore\Ext\Routers\IMedia::URL_PARAM_MEDIA_VERSION;
	$index = 0;

?><div class="mc-footer-navigation mc-footer-navigation-media"><?php
	echo $translate('Display:') . ' ';
	foreach ($mediaSiteKeysAndUrlPrefixes as $mediaVersion => $urlPrefix):
		if ($mediaVersion == $currentMediaSiteVersion):
			?><span><?=$translate($mediaVersion)?></span><?php
		else:
			?><a href="<?php echo $this->Url(
				'self',
				[$mediaVersionUrlParam  => $mediaVersion]
			); ?>"><?=$translate($mediaVersion)?></a><?php
		endif;
		if (++$index > 0 && $index < $mediaVersionsCount) echo ', ';
	endforeach;
?></div>
