<?php
	/** @var $this \MvcCore\View */

	/** @var $router \MvcCore\Ext\Routers\ILocalization */
	$router = $controller->GetRouter();
	/** @var $request \MvcCore\Request */
	$request = $controller->GetRequest();
	
	$allowedLocalizations = $router->GetAllowedLocalizations();
	$localizationsCount = count($allowedLocalizations);
	$fullUrl = $request->GetFullUrl();
	$localizationUrlParam = \MvcCore\Ext\Routers\ILocalization::URL_PARAM_LOCALIZATION;

?><div class="mc-footer-navigation mc-footer-navigation-localization"><?php
	echo '<label>' . $translate('Change language:') . ' </label>';
	foreach ($allowedLocalizations as $index => $localization):
		if ($index > 0 && $index < $localizationsCount) 
			echo ', ';
		if ($localization == $currentLocalization):
			?><span><?=$translate('Language: ' . $localization)?></span><?php
		else:
			?><a href="<?php echo $this->Url(
				'self',
				[$localizationUrlParam  => $localization]
			); ?>"><?=$translate('Language: ' . $localization)?></a><?php
		endif;
	endforeach;
?></div>
