<table class="cd-collection-items theme">
	<thead>
		<tr>
			<th class="right"><?=$translate('Id')?></th>
			<th><?=$translate('Title')?></th>
			<th><?=$translate('Interpret')?></th>
			<th class="right"><?=$translate('Year')?></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($albums as $id => $album): ?>
			<tr>
				<td class="right"><?=$album->Id?></td>
				<td><a href="<?=$url(':Edit', ['id'	=> $album->Id])?>"><?=$escape($album->Title)?></a></td>
				<td><?=$escape($album->Interpret)?></td>
				<td class="right"><?=$escape($album->Year)?></td>
				<td class="center">
					<form class="delete" action="<?=$url(':Delete', ['absolute' => TRUE])?>" method="post">
						<input type="hidden" name="<?=$this->csrfName?>" value="<?=$this->csrfValue?>" />
						<input type="hidden" name="id" value="<?=$album->Id?>" />
						<input type="submit" value="<?=$translate('Delete')?>" />
					</form>
				</td>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>
