<?php /** @var \MvcCore\View $this */ ?>
<?php /** @var $albums \App\Models\Album[] */ ?>

<a 
	class="head-btn btn btn-wide btn-no-visiting" 
	href="<?=$url(':Create')?>"><span><b><?=$translate('New album')?></b></span></a>

<h1><?=$translate('CD Collection')?></h1>

<?php if (!$albums): ?>
	<p><?=$translate("No albums in database. To create, click to 'New Album' button.")?></p>
<?php else: ?>
	<p><?=$translate("Found {count} results.", ['count' => count($albums)])?></p>
	<?=$this->RenderScript('./index.table.' . $currentMediaSiteVersion)?>
<?php endif; ?>
